### ISSUE TITLE
用postman试了下，看了body给我msg是请求不合法

### ISSUE THREAD

**Issue by zhengkw** [white-shiro-bai/ghost_sa#10]
http://192.168.1.91:17988/gif.sa?project=test_app&remark=ben 我的请求是这个 flask里面配置的是0.0.0.0 端口17988 按照文档里的提示，使用这样的url请求，但是返回不合法，请问这个url需要怎么样才能上报成功呢。
操作步骤
我测试用的神策的 javaSDK ，将他里面走debug的api给小改了下，不让他拼接debug，开始测试，运行完他里面提供的HelloSensorsAnalytics，发现flask服务接收到了请求，并没有写入kafka和mysql。使用postman进行验证，发现返回body中的msg写的请求不合法，请问鬼策文档里也是按照这个格式进行请求，是哪里出了问题呢？

**Comment by white-shiro-bai** [comment]
环境配置好了之后，需要先执行/component/setup.py 创建表
然后执行flask_main.py 开始监听

你请求的地址 http://192.168.1.91:17988/**_### gif.sa_**?project=test_app&remark=ben 这里错误了 是sa.gif 不是 gif.sa。缓过来了试一下？接收到数据，控制台有输出的。

**Comment by zhengkw** [comment]
谢谢大佬，setup跑过了，看来是gif.sa的问题，我回头看看，是写的sa.gif还是gif.sa

Kevin

**Comment by white-shiro-bai** [comment]
不是大佬哟。大家共同学习，有问题我会跟进的。嘿嘿。
