### ISSUE TITLE
是否兼容所有神策SDK的上报？

### ISSUE THREAD

**Issue by larnsan** [white-shiro-bai/ghost_sa#2]
是否兼容所有神策SDK的上报？还是只支持IOS，JS，小程序，Python的SDK上报

**Comment by white-shiro-bai** [comment]
理论上兼容所有神策的sdk上报。但是我只测试了ios.js.python和小程序。
神策我只看到三种数据上报，get单条，post单条，post多条，目前是都兼容了的。

**Comment by white-shiro-bai** [comment]
@larnsan 理论上兼容所有神策的sdk上报。但是我只测试了ios.js.python和小程序。
神策我只看到三种数据上报，get单条，post单条，post多条，目前是都兼容了的。

**Comment by white-shiro-bai** [comment]
> 是否兼容所有神策SDK的上报？还是只支持IOS，JS，小程序，Python的SDK上报

刚刚测试过了原生安卓SDK上报，目前也未发现问题。
