### ISSUE TITLE
pymysql链接不释放

### ISSUE THREAD

**Issue by white-shiro-bai** [white-shiro-bai/ghost_sa#24]
系统大量数据库连接不释放，造成效率降低。大量TIME_WAIT

后续计划引入数据库连接池。

**Comment by phillip2019** [comment]
建议采用sqlalchemy成熟orm插件，提高效率，专注核心业务。

**Comment by white-shiro-bai** [comment]
> 建议采用sqlalchemy成熟orm插件，提高效率，专注核心业务。

原来的写法确实不好，有两个显著缺陷，一个是递归了，另外每次都释放浪费时间，要改进。
不过这个不释放的问题我找到了，其实是释放了。导致卡3000并发的限制是因为我前面的tidb接了slb，slb有并发限制造成的。 @phillip2019
