### ISSUE TITLE
数据库重试时造成进程整体卡住

### ISSUE THREAD

**Issue by white-shiro-bai** [white-shiro-bai/ghost_sa#26]
多进程入库时，一个进程因为时间戳冲突，造成重试时，所有进程都会卡住几分钟。该问题仅在使用kafka或多进程时出现。如果使用多线程组件，则无此问题。

**Comment by phillip2019** [comment]
有场景复现代码吗？逻辑上这个不可能

**Comment by white-shiro-bai** [comment]
> 有场景复现代码吗？逻辑上这个不可能
你说的没错，这个确实误判了。两个原因造成
1.不是数据库的问题，是写的太快，kafka的metadata没跟上，造成的等待，连接器里增加,metadata_max_age_ms= 1 * 60 * 1000 把等待时间从默认的5分钟改为1分钟，解决此问题。
2.tidb前面接了slb。结果阿里的slb默认3000并发，结果连不上数据库卡了。不用slb，直接连数据库，随机多选一，性能就上去了。
@phillip2019
