### ISSUE TITLE
不支持beacon方式上报数据

### ISSUE THREAD

**Issue by white-shiro-bai** [white-shiro-bai/ghost_sa#27]

**Comment by phillip2019** [comment]
beacon上报数据为ping方式上报，优点为就算用户关闭浏览器，beacon也能成功上报，避免丢失数据，其上报格式为content-type: text/plain, playload格式为data=xxx&crc=xxx

**Comment by white-shiro-bai** [comment]
感谢提供解决方案。合了个粗暴的版本。后续会在解决性能时候，再优化这块。

**Comment by zhj9709** [comment]
@white-shiro-bai 使用gif图上报有个很致命的问题，就是只要安装了广告过滤插件，几乎100%直接block掉。
