### ISSUE TITLE
您好，刚开始接触鬼策，之前神策sdk的相关文档也没找到，想咨询一下distinct_id是什么时候被置换成用户id的？是通过check_exist接口吗？

### ISSUE THREAD

**Issue by c8679724** [white-shiro-bai/ghost_sa#50]
如题，如果您方便可以提供微信联系方式或者有相关微信群。目前对distinct_id和设备信息、用户信息的转换比较迷茫，需要了解才能继续使用。感谢

**Comment by white-shiro-bai** [comment]
你好，关于神策的用户绑定与信息转换，可以参考这一篇
https://github.com/white-shiro-bai/ghost_sa/wiki/%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B

如何创建绑定关系，可以参考这一篇，神策所有的SDK基本都是login和logout方法负责切换登录与非登录状态
https://manual.sensorsdata.cn/sa/latest/zh_cn/tech_sdk_client_mp_api-7551849.html

可以加我微信 Ben_Xiaobai 加群。加我的时候请备注一下github。

感谢使用。
