### ISSUE TITLE
按照文档执行不下去啊，建库建不了，用的mysql5.7

### ISSUE THREAD

**Issue by semizhou** [white-shiro-bai/ghost_sa#6]
报错信息如下：
1. Specified key was too long; max key length is 3072 bytes
2. Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. 
3. {project_name}_user表的字段 all_user_profile 字段类型怎么是json类型？

**Comment by white-shiro-bai** [comment]
1.这个是主键过长造成的。因为一直在用TiDB调试，这个问题忽略了，我测试一下会尽快修复。

**Comment by white-shiro-bai** [comment]
2.这个同问题1，我复现一看看。
3.这个字段是存用户信息的，神策SDK在做profile_set这个动作的时候，会传这个上来的。用来标记用户信息。这样就不用联合生产库也能查询有用户的一些固定维度的信息了。

**Comment by white-shiro-bai** [comment]
增加了一个setup_mysql.py的程序，专门在mysql的环境下安装。
不过因为mysql自身的限制，如果使用超长的第三方广告监测链接，或者超长的长链缩短链，会出现报错。
下一个版本会处理这些问题。不过强烈建议不要使用MySQL。使用TiDB哪怕是TiDB官方要求的最小配置，每天也可以稳定跑500万点。MySQL性能未知，估计会很差。

**Comment by semizhou** [comment]
谢谢，mysql只是先测试跑起来

**Comment by semizhou** [comment]
setup_mysql.py已经成功跑完了
