### ISSUE TITLE
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE if not EXISTS `shortcut` (\n    `project` varchar(255) DEFAULT NULL ' at line 9")

### ISSUE THREAD

**Issue by zhengkw** [white-shiro-bai/ghost_sa#9]
File "/home/impdatahd/anaconda3/envs/ghost/lib/python3.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE if not EXISTS `shortcut` (\n    `project` varchar(255) DEFAULT NULL ' at line 9")

During handling of the above exception, another exception occurred:

不知道大佬他们是怎么初始化的。

**Comment by zhengkw** [comment]
把隐藏的特殊字符干掉了就能初始化了，不过上报地址还不知道怎么确定，安卓的SDK那种的

**Comment by white-shiro-bai** [comment]
上报地址就看你怎么部署了。你部署的地址 /sa.gif就是上报地址了。
如你部署的域名是 http://<domain>/。则上报地址就是http://<domain>/sa.igf?project=创建时的项目名&remark=识别标记，不传的话数据库里默认normal。

**Comment by zhengkw** [comment]
好的 谢谢大佬指点
